// Copyright (c) 2026 Trent Polack. All Rights Reserved.
// Licensed under the MIT License.

#include "Systems/Conditions/SystemicCondition.h"

#include "Systems/SystemicCore.h"
#include "Systems/Events/SystemicEvent.h"

// Get the trait provider for the subject of the event, handling both actor and component-based implementations.
TScriptInterface<ISystemicTraitProvider> USystemicCondition::GetSubjectTraitProvider(const FSystemicEvent& Event, FSystemicTrace& Trace) const
{
	UObject* pSubjectObject = USystemicCore::GetEventObjectBySubject(Event, Subject);
	ISystemicTraitProvider* pSubjectTraitProvider = Cast<ISystemicTraitProvider>(pSubjectObject);
	if(!pSubjectTraitProvider)
	{
		// There was no trait provider on the object, attempt to find it on the actor.
		if(AActor* pSubjectActor = Cast<AActor>(pSubjectObject))
		{
			pSubjectObject = pSubjectActor->FindComponentByInterface(USystemicTraitProvider::StaticClass());
			pSubjectTraitProvider = Cast<ISystemicTraitProvider>(pSubjectObject);
		}
	}

	if(!pSubjectTraitProvider)
	{
		// Subject does not implement ISystemicTraitProvider. Log this in the trace and return nullptr.
		Trace.EvaluatedConditionResults.Add(FSystemicTraceEvaluatedConditionResult(const_cast<USystemicCondition*>(this), false, TEXT("Subject does not implement ISystemicTraitProvider.")));
		return nullptr;
	}

	// Set both parts of the script interface.
	TScriptInterface<ISystemicTraitProvider> SubjectTraitProviderInterface;
	SubjectTraitProviderInterface.SetObject(pSubjectObject);
	SubjectTraitProviderInterface.SetInterface(pSubjectTraitProvider);
	return SubjectTraitProviderInterface;
}

#if WITH_EDITOR
// Generate and set a name and description for this condition based on its configuration.
void USystemicCondition::GenerateNameAndDescription()
{
	// Set a default condition name.
	ConditionName = *FString::Printf(TEXT("%s (Enabled: %s)"), *GetClass()->GetName(), bEnabled ? TEXT("true") : TEXT("false"));
		
	// Set a default condition description.
	ConditionDescription = FString::Printf(TEXT("%s (Subject:%s, Enabled: %s)."), *GetClass()->GetName(), *UEnum::GetValueAsString(Subject), bEnabled ? TEXT("true") : TEXT("false"));
		
	bAutoGeneratedConditionName = true;
	bAutoGeneratedConditionDescription = true;
}
#endif

// Base condition evaluation; so long as it's enabled and the data is valid it'll pass.
bool USystemicCondition::Evaluate(const FSystemicEvent& Event, FSystemicRuleContext& Context, FSystemicTrace& Trace) const
{
	FSystemicTraceEvaluatedConditionResult result(const_cast<USystemicCondition*>(this));
	result.bResult = bEnabled && (((Subject == ESystemicEventSubject::Instigator) && Event.Instigator.IsValid())
		|| (Subject == ESystemicEventSubject::Target && Event.Target.IsValid())
		|| (Subject == ESystemicEventSubject::Source && Event.Source.IsValid()));
	
	if(result.bResult)
	{
		result.EvaluationLog.Add(FString::Printf(TEXT("Condition (%s): enabled.\n\tResult: Success."), *ConditionName.ToString()));
	}
	else
	{
		result.EvaluationLog.Add(FString::Printf(TEXT("Condition (%s): enabled.\n\tResult: Failure."), *ConditionName.ToString()));
	}

	return(result.bResult);
}