// Copyright (c) 2026 Trent Polack. All Rights Reserved.
// Licensed under the MIT License.

#include "Systems/Reactions/SystemicReaction.h"

#include "Systems/SystemicTrace.h"

#include "Systems/Events/SystemicEvent.h"

// USystemicReaction Constructor.
USystemicReaction::USystemicReaction()
{
	if(!ReactionName.IsValid() && !bAutoGeneratedReactionName)
	{
		// Set a default condition name.
		//	TODO (trent, 5/24/26): Should make this an editor function.
		ReactionName = *FString::Printf(TEXT("%s"), *GetClass()->GetName());
		
		bAutoGeneratedReactionName = true;
	}
}

// Accessor for the reaction name.
const FName& USystemicReaction::GetReactionName() const
{
	return ReactionName;
}

// Execute this reaction from the triggering event, cached data in the rule context, and built-up trace information. The base implementation will just log that it has been executed.
bool USystemicReaction::Execute(const FSystemicEvent& Event, FSystemicRuleContext& Context, FSystemicTrace& Trace)
{
	Trace.RuleReactionNameAndResultList.Add(TPair<FName, bool>(GetReactionName(), true));
	return true;
}