// Copyright (c) 2026 Trent Polack. All Rights Reserved.
// Licensed under the MIT License.

#pragma once

#include "CoreMinimal.h"

#include "UObject/Object.h"

#include "Systems/SystemicTrace.h"
#include "Systems/Events/SystemicEvent.h"

#include "SystemicReaction.generated.h"

// Declarations.
struct FSystemicRuleContext;
struct FSystemicTrace;

/**
 *	USystemicReaction Class Definition.
 *		Object that contains a Reaction which can take in a systemic event and evaluate it.
 */
UCLASS(Abstract, Blueprintable, BlueprintType, EditInlineNew, Category="Game|Systems", ClassGroup=(JoyCore))
class JOYCORE_API USystemicReaction : public UObject
{
	GENERATED_BODY()

protected:
	// Name of this Reaction; used for identification and organization. It does not affect functionality.
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Reaction|Config", meta = (DisplayPriority = "1"))
	FName ReactionName = NAME_None;

	// Whether this Reaction is currently enabled; this is more for ease-of-management in larger Rule definitions (default: true).
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Reaction|Config", meta = (DisplayAfter = "ReactionName"))
	uint8 bEnabled : 1 = true;

	// Whether the reaction name was procedurally generated.
	uint8 bAutoGeneratedReactionName : 1 = false;
	
public:
	/**
	 * Accessor for the reaction name.
	 * @returns The name of this reaction.
	 */
	UFUNCTION(BlueprintCallable, Category="Game|Systems|Reactions")
	const FName& GetReactionName() const;

#if WITH_EDITOR
	/**
	 * Generate and set a name for this rule based on the reaction's configuration.
	 */
	UFUNCTION(BlueprintCallable, CallInEditor, Category="Reaction")
	virtual void GenerateName();
#endif
	
	/**
	 * Execute this reaction from the triggering event, cached data in the rule context, and built-up trace information. The base implementation will just log that it has been executed.
	 * @param Event Triggering event.
	 * @param Context Cached data from the rule context.
	 * @param Trace Trace information for debugging and logging.
	 * @returns True if the execution is complete, false if there's an error along the way.
	 */
	UFUNCTION(BlueprintCallable, Category="Game|Systems|Reactions")
	virtual bool Execute(const FSystemicEvent& Event, FSystemicRuleContext& Context, FSystemicTrace& Trace);
};