// Copyright (c) 2026 Trent Polack. All Rights Reserved.
// Licensed under the MIT License.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimTrace.h"

#include "GameFramework/Actor.h"
#include "UObject/Object.h"

#include "Systems/Traits/ISystemicTraitProvider.h"
#include "Systems/Events/SystemicEvent.h"
#include "Systems/SystemicTrace.h"

#include "SystemicCondition.generated.h"

// Declarations.
struct FSystemicRuleContext;

/**
 *	USystemicCondition Class Definition.
 *		Object that contains a condition which can take in a systemic event and evaluate it.
 */
UCLASS(Blueprintable, BlueprintType, Abstract, EditInlineNew, Category="Game|Systems", ClassGroup=(JoyCore))
class JOYCORE_API USystemicCondition : public UObject
{
	GENERATED_BODY()

protected:
	// Name of this Condition; use for identification and organization. It does not affect functionality.
	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "Condition|Config", meta = (DisplayPriority = "1"))
	FName ConditionName = NAME_None;

	// Description of what this Condition is doing; useful for in-line documentation. It does not affect functionality.
	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "Condition|Config", meta = (DisplayAfter = "ConditionName"))
	FString ConditionDescription = FString();
	
	// Subject that this condition is evaluating against.
	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "Condition|Config")
	ESystemicEventSubject Subject = ESystemicEventSubject::Source;

	// Whether this Condition is enabled and should be evaluated (default: true).
	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "Condition|Config", meta=(DisplayAfter="Description"))
	uint8 bEnabled : 1 = true;

	uint8 bAutoGeneratedConditionName : 1 = false;
	uint8 bAutoGeneratedConditionDescription : 1 = false;
	
public:
	/**
	 *	Get the trait provider interface for the subject of the given event.
	 *	@param Event Triggering event.
	 *	@param Trace Trace information for debugging and logging.
	 *	@returns Trait provider for the subject; return nullptr if the subject does not implement ISystemicTraitProvider.
	 */
	UFUNCTION(BlueprintCallable, Category="Game|Systems|Conditions")
	TScriptInterface<ISystemicTraitProvider> GetSubjectTraitProvider(const FSystemicEvent& Event, FSystemicTrace& Trace) const;
	
#if WITH_EDITOR
	/**
	 * Generate and set a name and description for this condition based on its configuration.
	 */
	UFUNCTION(BlueprintCallable, CallInEditor, Category="Condition")
	virtual void GenerateNameAndDescription();
#endif

	/**
	 * Evaluate this condition given the triggering event, cached data in the rule context, and built-up trace information. The base implementation will do a check to ensure the condition is enabled and the subject is valid (so it works as a basic null check).
	 * @param Event Triggering event.
	 * @param Context Cached data from the rule context.
	 * @param Trace Trace information for debugging and logging.
	 * @returns True if the condition is met, false otherwise.
	 */
	UFUNCTION(BlueprintCallable, Category="Game|Systems|Conditions")
	virtual bool Evaluate(const FSystemicEvent& Event, FSystemicRuleContext& Context, FSystemicTrace& Trace) const;
};
